<?php

/**
 * Noupia Pay API - PHP code sample.
 *
 * HOW TO GET YOUR API KEYS
 * 1. Open your Noupia app (Make sure your account is verified and activated)
 * 2. Visit the "Account" page
 * 3. Scroll to the bottom and tap the version number 3 times
 * 4. Tap the "View Key" button and copy your keys to clipboard.
 * 5. Paste your copied keys below
 * 
 * For more details, please
 * Visit the API documentation at: https://noupia.com/developers/pay
 * 
 * @author Noupia Limited (N.P LTD)
 * @since 1.2.0
 * @link https://noupia.com/developers
 * @copyright Copyright (c) 2023 Noupia Limited <info@noupia.com> 
 * 
 */


define('DEVELOPER_KEY', 'YOUR_NOUPIA_DEVELOPER_KEY_HERE');
define('SUBSCRIPTION_KEY', 'YOUR_NOUPIA_PAY_SUBSCRIPTION_KEY_HERE');


/**
 * The function to initiate a Noupia Pay transaction
 *
 * @return object A server response on success/error
 */
function initiateNoupiaPayment()
{
	$curl = curl_init();
    curl_setopt_array($curl, [
    CURLOPT_URL 		   => 'https://api.noupia.com/pay',
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING 	   => "",
    CURLOPT_MAXREDIRS 	   => 10,
    CURLOPT_TIMEOUT 	   => 30,
    CURLOPT_HTTP_VERSION   => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST  => "POST",
    CURLOPT_POSTFIELDS     => json_encode([
    	// (string) [required] Specify the operation "initiate"
    	'operation'	 	=> 'initiate', 		
    	// (string) [required] Item reference e.g SCHOOL FEES			 
    	'reference'     => 'YOUR_ITEM_REFERENCE_HERE',   
    	// (int) [required] Item cost
        'amount' 		=> 100, 	
        // (int) [required] Mobile Money account number. No phone code.					 
        'phone' 		=> 671234567, 	
        // (string) [required] Payment method: mobilemoney, noupia, invoice or withdraw.
        //(WARNING: "withdraw" will transfer funds to the Mobile Money account number "phone" provided)			 
        'method' 		=> 'mobilemoney', 	
        // (string) [optional] Customer country code (iso-2 format)	e.g CM, NG, SN, FR, US		 
        'country' 		=> 'CM', 
        // (string) [optional] Charge currency. Default is XAF. Visit https://noupia.com/rates for currency exchange rates					 
        'currency' 		=> 'XAF',	
        // (string) [optional] Your customer's email address. If provided, a receipt will be sent to customer upon successful payment.					 
        'email' 		=> 'your.customer@email.com',  
        // (string) [optional] Your customer's name.  E.g John Doe
        'name' 			=> 'YOUR CUSTOMER NAME',		 
    ]),
    CURLOPT_HTTPHEADER => [
            'Accept: */*',
            'Content-Type: application/json',
            'Noupia-API-Signature: np-live',
            'Noupia-API-Key: '.DEVELOPER_KEY,
            'Noupia-Product-Key: '.SUBSCRIPTION_KEY
        ],
    ]);
    
    $response = curl_exec($curl);
    $error = curl_error($curl);
    $close = curl_close($curl);

    if ($error) {
        printf('cURL Error :%s', $error);
    }
    else {
        $result = json_decode($response);

        /**
         * Example of a failed JSON response
         * {
			  "response": "error",
			  "code": "PAYMENT_INIT_ERROR",
			  "message": "Oops, payment could not be initiated. Verify parameters and try again.",
			  "data": null
			}
         * 
         * Example of a successful JSON response
         * {
			  "response": "success",
			  "code": "OPERATION_SUCCESSFUL",
			  "message": "Payment initiated successfully ✔",
			  "data": {
			    "transaction": "PAYCM020320231258210916331657",
			    "channel_ussd": "*126#",
			    "channel_name": "CM MTN MOBILEMONEY"
			  }
			}
         * 
         */

		$responseStatus = $result->response; 	      // "success" or "error"
		$responseMessage = $result->message; 		  // A detailed description of the response

		$transactionId = $result->data->transaction;
		/**
		 * A unique transaction ID generated by Noupia. 
		 * This will later be used to verify the status of the payment.
		 * Save this $transactionId in your system for later use in the function "verifyNoupiaPayment()"
		 * 
		 */
    }
}




/**
 * The function to verify a Noupia Pay transaction
 *
 * @return object A server response on success/error
 */

function verifyNoupiaPayment()
{
	$curl = curl_init();
    curl_setopt_array($curl, [
    CURLOPT_URL 		   => 'https://api.noupia.com/pay',
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING 	   => "",
    CURLOPT_MAXREDIRS 	   => 10,
    CURLOPT_TIMEOUT 	   => 30,
    CURLOPT_HTTP_VERSION   => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST  => "POST",
    CURLOPT_POSTFIELDS     => json_encode([
    	'operation'	 	   => 'verify', 					   // (string) [required] Specify the operation "verify"
    	'transaction'      => 'PAYCM050320231328588367392783', // (string) [required] Transaction ID returned by Noupia.
    ]),
    CURLOPT_HTTPHEADER => [
            'Accept: */*',
            'Content-Type: application/json',
            'Noupia-API-Signature: np-live',
            'Noupia-API-Key: '.DEVELOPER_KEY,
            'Noupia-Product-Key: '.SUBSCRIPTION_KEY
        ],
    ]);
    
    $response = curl_exec($curl);
    $error = curl_error($curl);
    $close = curl_close($curl);

    if ($error) {
        printf('cURL Error :%s', $error);
    }
    else {
        $result = json_decode($response);

        /**
         * Example of a successful JSON response;
         * 
         * {
			  "response": "success",
			  "code": "OPERATION_SUCCESSFUL",
			  "message": "Transaction was completed successfully ✔",
			  "data": {
			    "transaction": "PAYCM050320231328588367392783",
			    "type": "pay",
			    "status": "successful",
			    "amount": "100",
			    "fee": "2",
			    "currency": "XAF",
			    "reference": "GARRI AND ERU",
			    "description": "MOBILEMONEY 671234567",
			    "date": "05-03-2023",
			    "time": "13:29:03",
			    "timestamp": 1678019343,
			    "method": "MOBILEMONEY",
			    "payer": "671234567",
			    "call": "API",
			    "country": "CM",
			    "ip": "661.29.147.22",
			    "metadata": "omarestaurant"
			  }
			}
         * 
         */

		$transactionStatus = $result->data->status;
		/**
		 * $transactionStatus value will be;
		 *  
		 * "successful" if the payment was completed by customer.
		 * "failed" 	if the payment was timed out or customer cancelled.
		 * "pending" 	if the customer is still to validate.
		 */
    }
}


/**
 * 
 * 
	The MIT License (MIT)

	Copyright (c) 2020-2023 Noupia Limited <info@noupia.com>

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in
	all copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
	THE SOFTWARE.
*
*/